kind: pipeline
type: docker
name: Pipeline-CI/CD

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: docker-username
    password: docker-secret
    repo: pereirafmauro/chopp-ti
    dockerfile: Docker/
    tags:
    - latest
