kind: pipeline
type: kubernetes
name: Projeto-CI/CD

steps:
  - name: publish
    image: plugins/docker
    privileged: true
    settings:
      repo: pereirafmauro/choppti
      dockerfile: Docker/
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      tags:
        - latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
