kind: pipeline
type: kubernetes
name: Projeto-CI/CD

steps:

  - name: Start Notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: Iniciado a pipeline de CI

  - name: Build & Push Registry
    image: plugins/docker
    privileged: true
    settings:
      repo: pereirafmauro/choppti
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      tags:
        - ${DRONE_COMMIT}

  - name: Termination Notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: Imagem enviada para o registry com sucesso !

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
