kind: pipeline
type: kubernetes
name: Projeto-CI/CD 

steps:

- name: Start Notification CI
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: webhook_id
    webhook_token:
      from_secret: webhook_token
    message: Iniciando etapa de CI

- name: Build & Push Registry
  image: plugins/docker
  privileged: true
  settings:
    repo: pereirafmauro/choppti
    username:
      from_secret: docker-username
    password:
      from_secret: docker-password
    tags:
      - ${DRONE_COMMIT}

- name: Trivy Scan
  image: aquasec/trivy:latest
  commands:
    - trivy image --no-progress --format json pereirafmauro/choppti:${DRONE_COMMIT} > trivy-report.json

- name: Send Trivy Report to Discord
  image: alpine:latest
  commands:
    - apk update
    - apk add curl
    - apk add jq
    - |
      WEBHOOK_URL=${DISCORD_WEBHOOK_URL}

      MESSAGE=$(cat trivy-report.json | jq -r '
        .Results[] |
        "Target: \(.Target)\n" +
        (.Vulnerabilities[] | "\(.VulnerabilityID): \(.PkgName) - Severity: \(.Severity) - Title: \(.Title)") |
        join("\n")
        ')

      curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Trivy Scan Results:\n$MESSAGE\"}" $WEBHOOK_URL
  environment:
    DISCORD_WEBHOOK_URL:
      from_secret: discord_webhook_url

- name: Termination Notification CD
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: webhook_id
    webhook_token:
      from_secret: webhook_token
    message: >
      {{#success build.status}}
        Imagem enviada para o registry com sucesso ! Imagem pereirafmauro/choppti:${DRONE_COMMIT}
      {{else}}
        Erro no envio da imagem para o registry !
        {{/success}}

- name: Commit and changes to the CD repo
  image: pereirafmauro/choppti-commiter:latest
  commands:
  - cd /root/cd-choppti
  - git pull
  - cd chopp-ti/templates
  - sed -E -i.bak 's%(pereirafmauro/choppti:).*%pereirafmauro/choppti:${DRONE_COMMIT}%' deploy.yml
  - git status
  - git add .
  - git commit -m "Atualizando a imagem do chart com a imagem pereirafmauro/choppti:${DRONE_COMMIT}"
  - git push

- name: Termination Notification pipeline
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: webhook_id
    webhook_token: 
      from_secret: webhook_token
    message: Deploy realizado com sucesso !

trigger:
  branch:
  - main

image_pull_secrets:
- dockerconfig

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
