kind: pipeline
type: kubernetes
name: Projeto-CI/CD

steps:

  - name: Start Notification CI
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: Iniciando etapa de CI

  - name: Build & Push Registry
    image: plugins/docker
    privileged: true
    settings:
      repo: pereirafmauro/choppti
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      tags:
        - ${DRONE_COMMIT}

  - name: Termination Notification CD
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: >
        {{#success build.status}}
          Imagem enviada para o registry com sucesso ! Imagem pereirafmauro/choppti:${DRONE_COMMIT}
        {{else}}
          Erro no envio da imagem para o registry !
         {{/success}}

  - name: Commit and changes to the CD repo
    image: pereirafmauro/choppti-commiter:latest
    commands:
    - cd /root/cd-choppti/app-choppti-chart/
    - git pull
    - sed -E -i.bak 's%(tag:).*%tag:${DRONE_COMMIT}%' values.yaml
    - git add .
    - git commit -m "Atualizando a imagem do chart"
    - git push

  - name: Termination Notification pipeline
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: Deploy realizado com sucesso !

image_pull_secrets:
- dockerconfig

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
