kind: pipeline
type: kubernetes
name: Projeto-CI/CD

steps:

  - name: Start Notification CI
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: Iniciado a pipeline de CI

  - name: Build & Push Registry
    image: plugins/docker
    privileged: true
    settings:
      repo: pereirafmauro/choppti
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
      tags:
        - ${DRONE_COMMIT}

  - name: Termination Notification CD
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: >
        {{#success build.status}}
          Imagem enviada para o registry com sucesso ! Imagem pereirafmauro/choppti${DRONE_COMMIT}
        {{else}}
          Erro no envio da imagem para o registry !
         {{/success}}

  - name: Commit and changes to the CD repo
    image_pull_secrets:
    - dockerconfig
    image: uzieljr/plugin-drone:5.0
    commands:
    - cd /root/cd-choppti/app-choppti-chart/templates
    - git pull

  - name: Termination Notification pipeline
    image: appleboy/drone-discord
    settings:
      webhook_id: 1261804379166740521
      webhook_token: AUePsMgaol3N1fpuInkgXP-vyW_7R_N29b4i9Z9uH8y2H1XxVkzHPQ26xQTzORo327fR
      message: >
        {{#success build.status}}
          Deploy feito com sucesso, aplicação via ArgoCD atualizado --> http://chopp-ti.techub.com/
        {{else}}
          Erro no deploy !!!
         {{/success}}  

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
