pipeline:
  identifier: Build_mauropereirafilho1_ci_choppti_1720787092980
  name: Build ci-choppti
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720787073858
        repoName: mauropereirafilho1/ci-choppti
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Build Image
                  spec:
                    shell: Sh
                    command: docker build -t pereirafmauro/chopp-ti:v1 -f /Drone
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: pereirafmauro/chopp-ti
                    tags:
                      - v1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
